FROM node:22-alpine3.19

WORKDIR /app

RUN apk add --no-cache bash curl dos2unix

COPY socket-service/package.json ./

RUN npm install

COPY socket-service ./

ENTRYPOINT [ "npm", "run", "start:dev" ]
