CREATE TABLE IF NOT EXISTS Project (
    Id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    Name VARCHAR(250) NOT NULL,
    Description VARCHAR(1024) NOT NULL,
    Metadata JSONB DEFAULT NULL,
    Progress INTEGER DEFAULT 0, 
    Created_At TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
